import ast
import operator
import re
import subprocess
from pathlib import Path

PROJECT_ROOT     = Path(__file__).resolve().parents[3]
GENERATED_ROOT   = Path(__file__).resolve().parents[2] / "generated_projects"


def safe_path(path: str) -> Path:
    clean = path.strip().strip('"').strip("'")
    target = (PROJECT_ROOT / clean).resolve()
    if not str(target).startswith(str(PROJECT_ROOT)):
        raise PermissionError("Access denied.")
    return target


def run_python(code: str) -> str:
    try:
        r = subprocess.run(
            ["python", "-c", code],
            capture_output=True,
            text=True,
            timeout=5,
        )
        return r.stdout or r.stderr or "No output"
    except Exception as e:
        return str(e)


_ALLOWED_OPS = {
    ast.Add: operator.add,
    ast.Sub: operator.sub,
    ast.Mult: operator.mul,
    ast.Div: operator.truediv,
    ast.Pow: operator.pow,
    ast.USub: operator.neg,
}


def _eval_math(node):
    if isinstance(node, ast.Constant):
        return node.value
    if isinstance(node, ast.BinOp):
        return _ALLOWED_OPS[type(node.op)](
            _eval_math(node.left),
            _eval_math(node.right),
        )
    if isinstance(node, ast.UnaryOp):
        return _ALLOWED_OPS[type(node.op)](_eval_math(node.operand))
    raise ValueError("Invalid expression")


def calculator(expr: str) -> str:
    try:
        tree = ast.parse(expr, mode="eval")
        return str(_eval_math(tree.body))
    except Exception as e:
        return str(e)


def read_file(path: str) -> str:
    try:
        target = safe_path(path)
        if not target.exists():
            return f"File not found: {path}"
        if target.is_dir():
            return f"{path} is a folder."
        return target.read_text(encoding="utf-8", errors="ignore")
    except Exception as e:
        return str(e)


def write_file(payload: str) -> str:
    try:
        path, content = payload.split("\nCONTENT:\n", 1)
        target = safe_path(path)
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(content, encoding="utf-8")
        return f"File written: {target.relative_to(PROJECT_ROOT)}"
    except Exception as e:
        return str(e)


def append_file(payload: str) -> str:
    try:
        path, content = payload.split("\nCONTENT:\n", 1)
        target = safe_path(path)
        target.parent.mkdir(parents=True, exist_ok=True)
        with target.open("a", encoding="utf-8") as f:
            f.write(content)
        return f"Content appended: {target.relative_to(PROJECT_ROOT)}"
    except Exception as e:
        return str(e)


def _project_name(raw: str) -> str:
    clean = (
        raw.strip()
        .lower()
        .replace("build project:", "")
        .replace("create project:", "")
        .replace("build api:", "")
        .replace("create api:", "")
        .replace("api:", "")
        .replace("fullstack", "")
        .replace("full stack", "")
        .replace("with database", "")
        .replace("advanced", "")
        .strip()
        .replace(" ", "_")
        .replace("-", "_")
    )
    return clean or "new_project"


def _write(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")


def _basic_fastapi_project(root: Path, name: str) -> str:
    _write(
        root / "README.md",
        f"# {name}\n\nGenerated by IntelliYash Builder.\n\nRun:\n\npip install -r requirements.txt\npython app.py\n",
    )

    _write(
        root / "app.py",
        """from fastapi import FastAPI
import uvicorn

app = FastAPI(title="Generated App")

items = []

@app.get("/")
def home():
    return {"message": "Hello from generated project"}

@app.get("/items")
def list_items():
    return {"items": items}

@app.post("/items")
def add_item(name: str):
    item = {"id": len(items) + 1, "name": name}
    items.append(item)
    return item

if __name__ == "__main__":
    uvicorn.run(app, host="127.0.0.1", port=9000)
""",
    )

    _write(root / "requirements.txt", "fastapi\nuvicorn\n")

    rel = root.relative_to(PROJECT_ROOT)
    return f"""Basic FastAPI project created: {rel}

Files:
- README.md
- app.py
- requirements.txt

Run:

cd {rel}
pip install -r requirements.txt
python app.py
"""


def _smart_api_project(root: Path, name: str) -> str:
    _write(
        root / "README.md",
        f"""# {name} API

Generated by IntelliYash Smart API Generator.

Run:

pip install -r requirements.txt
python main.py

Docs:

http://127.0.0.1:9300/docs

Endpoints:
- GET /
- GET /items
- POST /items
- GET /items/{{item_id}}
- PUT /items/{{item_id}}
- DELETE /items/{{item_id}}
""",
    )

    _write(root / "requirements.txt", "fastapi\nuvicorn\npydantic\n")

    _write(
        root / "main.py",
        f"""from fastapi import FastAPI, HTTPException
from pydantic import BaseModel
import uvicorn

app = FastAPI(title="{name.title()} API")

items = []

class ItemCreate(BaseModel):
    name: str
    description: str = ""
    price: float = 0

class ItemUpdate(BaseModel):
    name: str | None = None
    description: str | None = None
    price: float | None = None

@app.get("/")
def home():
    return {{"message": "{name} API running"}}

@app.get("/items")
def list_items():
    return {{"items": items}}

@app.post("/items")
def create_item(data: ItemCreate):
    item = {{
        "id": len(items) + 1,
        "name": data.name,
        "description": data.description,
        "price": data.price,
    }}
    items.append(item)
    return item

@app.get("/items/{{item_id}}")
def get_item(item_id: int):
    for item in items:
        if item["id"] == item_id:
            return item
    raise HTTPException(status_code=404, detail="Item not found")

@app.put("/items/{{item_id}}")
def update_item(item_id: int, data: ItemUpdate):
    for item in items:
        if item["id"] == item_id:
            if data.name is not None:
                item["name"] = data.name
            if data.description is not None:
                item["description"] = data.description
            if data.price is not None:
                item["price"] = data.price
            return item
    raise HTTPException(status_code=404, detail="Item not found")

@app.delete("/items/{{item_id}}")
def delete_item(item_id: int):
    global items
    before = len(items)
    items = [item for item in items if item["id"] != item_id]
    if len(items) == before:
        raise HTTPException(status_code=404, detail="Item not found")
    return {{"status": "deleted", "id": item_id}}

if __name__ == "__main__":
    uvicorn.run(app, host="127.0.0.1", port=9300)
""",
    )

    rel = root.relative_to(PROJECT_ROOT)
    return f"""Smart API project created: {rel}

Files:
- README.md
- main.py
- requirements.txt

Run:

cd {rel}
pip install -r requirements.txt
python main.py

Docs:

http://127.0.0.1:9300/docs
"""


def _todo_fullstack_project(root: Path, name: str) -> str:
    backend = root / "backend"
    frontend = root / "frontend"

    _write(
        root / "README.md",
        f"""# {name}

Generated by IntelliYash Advanced Builder.

Backend:

cd backend
pip install -r requirements.txt
python main.py

Frontend:

Open frontend/index.html in browser.
""",
    )

    _write(
        backend / "main.py",
        """from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
import uvicorn

app = FastAPI(title="Todo API")

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

todos = []

@app.get("/")
def home():
    return {"message": "Todo API running"}

@app.get("/todos")
def list_todos():
    return {"todos": todos}

@app.post("/todos")
def create_todo(title: str):
    todo = {"id": len(todos) + 1, "title": title, "done": False}
    todos.append(todo)
    return todo

@app.put("/todos/{todo_id}")
def toggle_todo(todo_id: int):
    for todo in todos:
        if todo["id"] == todo_id:
            todo["done"] = not todo["done"]
            return todo
    return {"error": "Todo not found"}

@app.delete("/todos/{todo_id}")
def delete_todo(todo_id: int):
    global todos
    todos = [todo for todo in todos if todo["id"] != todo_id]
    return {"status": "deleted", "id": todo_id}

if __name__ == "__main__":
    uvicorn.run(app, host="127.0.0.1", port=9100)
""",
    )

    _write(backend / "requirements.txt", "fastapi\nuvicorn\n")

    _write(
        frontend / "index.html",
        """<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8" />
  <title>Todo App</title>
  <style>
    body { font-family: Arial; background: #f6f7fb; padding: 40px; }
    .app { max-width: 640px; margin: auto; background: white; padding: 24px; border-radius: 16px; box-shadow: 0 10px 30px rgba(0,0,0,.08); }
    input { padding: 12px; width: 70%; border: 1px solid #ddd; border-radius: 8px; }
    button { padding: 12px 14px; border: none; border-radius: 8px; background: #4f46e5; color: white; cursor: pointer; margin-left: 8px; }
    li { margin: 12px 0; padding: 12px; background: #f3f4f6; border-radius: 8px; display: flex; justify-content: space-between; align-items: center; }
    .done { text-decoration: line-through; opacity: .6; }
  </style>
</head>
<body>
  <div class="app">
    <h1>Todo App</h1>
    <input id="todoInput" placeholder="Write a todo..." />
    <button onclick="addTodo()">Add</button>
    <ul id="todos"></ul>
  </div>

  <script>
    const API = "http://127.0.0.1:9100";

    async function loadTodos() {
      const res = await fetch(API + "/todos");
      const data = await res.json();
      const list = document.getElementById("todos");
      list.innerHTML = "";

      data.todos.forEach(todo => {
        const li = document.createElement("li");
        const span = document.createElement("span");
        span.textContent = todo.title;
        if (todo.done) span.className = "done";

        const actions = document.createElement("div");

        const toggleBtn = document.createElement("button");
        toggleBtn.textContent = "Toggle";
        toggleBtn.onclick = async () => {
          await fetch(API + "/todos/" + todo.id, { method: "PUT" });
          loadTodos();
        };

        const delBtn = document.createElement("button");
        delBtn.textContent = "Delete";
        delBtn.onclick = async () => {
          await fetch(API + "/todos/" + todo.id, { method: "DELETE" });
          loadTodos();
        };

        actions.appendChild(toggleBtn);
        actions.appendChild(delBtn);
        li.appendChild(span);
        li.appendChild(actions);
        list.appendChild(li);
      });
    }

    async function addTodo() {
      const input = document.getElementById("todoInput");
      const title = input.value.trim();
      if (!title) return;

      await fetch(API + "/todos?title=" + encodeURIComponent(title), { method: "POST" });
      input.value = "";
      loadTodos();
    }

    loadTodos();
  </script>
</body>
</html>
""",
    )

    rel = root.relative_to(PROJECT_ROOT)
    return f"""Todo fullstack project created: {rel}

Files:
- README.md
- backend/main.py
- backend/requirements.txt
- frontend/index.html

Run backend:

cd {rel}\\backend
pip install -r requirements.txt
python main.py

Open frontend:

{rel}\\frontend\\index.html
"""


def _blog_api_project(root: Path, name: str) -> str:
    _write(
        root / "README.md",
        f"""# {name}

Generated Blog API.

Run:

pip install -r requirements.txt
python main.py

Docs:

http://127.0.0.1:9200/docs
""",
    )

    _write(root / "requirements.txt", "fastapi\nuvicorn\npydantic\n")

    _write(
        root / "main.py",
        """from fastapi import FastAPI, HTTPException
from pydantic import BaseModel
import uvicorn

app = FastAPI(title="Blog API")

posts = []

class PostCreate(BaseModel):
    title: str
    content: str
    author: str = "anonymous"

@app.get("/")
def home():
    return {"message": "Blog API running"}

@app.get("/posts")
def list_posts():
    return {"posts": posts}

@app.post("/posts")
def create_post(data: PostCreate):
    post = {
        "id": len(posts) + 1,
        "title": data.title,
        "content": data.content,
        "author": data.author,
    }
    posts.append(post)
    return post

@app.get("/posts/{post_id}")
def get_post(post_id: int):
    for post in posts:
        if post["id"] == post_id:
            return post
    raise HTTPException(status_code=404, detail="Post not found")

@app.delete("/posts/{post_id}")
def delete_post(post_id: int):
    global posts
    before = len(posts)
    posts = [p for p in posts if p["id"] != post_id]
    if len(posts) == before:
        raise HTTPException(status_code=404, detail="Post not found")
    return {"status": "deleted", "id": post_id}

if __name__ == "__main__":
    uvicorn.run(app, host="127.0.0.1", port=9200)
""",
    )

    rel = root.relative_to(PROJECT_ROOT)
    return f"""Blog API project created: {rel}

Files:
- README.md
- main.py
- requirements.txt

Run:

cd {rel}
pip install -r requirements.txt
python main.py

Docs:

http://127.0.0.1:9200/docs
"""


def _dashboard_project(root: Path, name: str) -> str:
    _write(
        root / "README.md",
        f"""# {name}

Generated dashboard UI.

Open:

index.html
""",
    )

    _write(
        root / "index.html",
        """<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8" />
  <title>Dashboard</title>
  <style>
    body { margin: 0; font-family: Arial; background: #0f172a; color: white; }
    .layout { display: grid; grid-template-columns: 240px 1fr; min-height: 100vh; }
    aside { background: #111827; padding: 24px; }
    main { padding: 32px; }
    .cards { display: grid; grid-template-columns: repeat(3, 1fr); gap: 18px; }
    .card { background: #1f2937; border-radius: 16px; padding: 22px; box-shadow: 0 10px 30px rgba(0,0,0,.25); }
    .big { font-size: 32px; font-weight: 800; margin-top: 10px; }
  </style>
</head>
<body>
  <div class="layout">
    <aside>
      <h2>Dashboard</h2>
      <p>Overview</p>
      <p>Users</p>
      <p>Settings</p>
    </aside>
    <main>
      <h1>Analytics Dashboard</h1>
      <div class="cards">
        <div class="card"><div>Total Users</div><div class="big">1,240</div></div>
        <div class="card"><div>Revenue</div><div class="big">$8,420</div></div>
        <div class="card"><div>Projects</div><div class="big">38</div></div>
      </div>
    </main>
  </div>
</body>
</html>
""",
    )

    rel = root.relative_to(PROJECT_ROOT)
    return f"""Dashboard project created: {rel}

Files:
- README.md
- index.html

Open:

{rel}\\index.html
"""


def _cli_project(root: Path, name: str) -> str:
    _write(
        root / "README.md",
        f"""# {name}

Generated CLI tool.

Run:

python cli.py hello
python cli.py add 5 7
""",
    )

    _write(
        root / "cli.py",
        """import argparse

def main():
    parser = argparse.ArgumentParser(description="Generated CLI Tool")
    sub = parser.add_subparsers(dest="command")

    hello = sub.add_parser("hello")
    hello.add_argument("--name", default="World")

    add = sub.add_parser("add")
    add.add_argument("a", type=float)
    add.add_argument("b", type=float)

    args = parser.parse_args()

    if args.command == "hello":
        print(f"Hello, {args.name}!")
    elif args.command == "add":
        print(args.a + args.b)
    else:
        parser.print_help()

if __name__ == "__main__":
    main()
""",
    )

    rel = root.relative_to(PROJECT_ROOT)
    return f"""CLI project created: {rel}

Files:
- README.md
- cli.py

Run:

cd {rel}
python cli.py hello --name IntelliYash
python cli.py add 5 7
"""


def _ecommerce_api_project(root: Path, name: str) -> str:
    _write(
        root / "README.md",
        f"""# {name} Ecommerce API

Generated by IntelliYash API Generator.

Run:

pip install -r requirements.txt
python main.py

Docs:

http://127.0.0.1:9400/docs

Generated:
- FastAPI app
- SQLite database
- SQLAlchemy models
- User CRUD
- Product CRUD
- Order create/list/get/delete
""",
    )

    _write(
        root / "requirements.txt",
        """fastapi
uvicorn
sqlalchemy
pydantic
email-validator
""",
    )

    _write(
        root / "database.py",
        """from sqlalchemy import create_engine
from sqlalchemy.orm import sessionmaker, declarative_base

DATABASE_URL = "sqlite:///./app.db"

engine = create_engine(
    DATABASE_URL,
    connect_args={"check_same_thread": False}
)

SessionLocal = sessionmaker(
    autocommit=False,
    autoflush=False,
    bind=engine
)

Base = declarative_base()


def get_db():
    db = SessionLocal()
    try:
        yield db
    finally:
        db.close()
""",
    )

    _write(
        root / "models.py",
        """from sqlalchemy import Column, Integer, String, Float, ForeignKey
from sqlalchemy.orm import relationship
from database import Base


class User(Base):
    __tablename__ = "users"

    id = Column(Integer, primary_key=True, index=True)
    name = Column(String, nullable=False)
    email = Column(String, unique=True, index=True, nullable=False)

    orders = relationship("Order", back_populates="user")


class Product(Base):
    __tablename__ = "products"

    id = Column(Integer, primary_key=True, index=True)
    name = Column(String, nullable=False)
    description = Column(String, default="")
    price = Column(Float, nullable=False)
    stock = Column(Integer, default=0)

    orders = relationship("Order", back_populates="product")


class Order(Base):
    __tablename__ = "orders"

    id = Column(Integer, primary_key=True, index=True)
    user_id = Column(Integer, ForeignKey("users.id"), nullable=False)
    product_id = Column(Integer, ForeignKey("products.id"), nullable=False)
    quantity = Column(Integer, default=1)
    total_price = Column(Float, nullable=False)

    user = relationship("User", back_populates="orders")
    product = relationship("Product", back_populates="orders")
""",
    )

    _write(
        root / "schemas.py",
        """from pydantic import BaseModel, EmailStr
from typing import Optional


class UserCreate(BaseModel):
    name: str
    email: EmailStr


class UserUpdate(BaseModel):
    name: Optional[str] = None
    email: Optional[EmailStr] = None


class UserRead(UserCreate):
    id: int

    class Config:
        from_attributes = True


class ProductCreate(BaseModel):
    name: str
    description: Optional[str] = ""
    price: float
    stock: int = 0


class ProductUpdate(BaseModel):
    name: Optional[str] = None
    description: Optional[str] = None
    price: Optional[float] = None
    stock: Optional[int] = None


class ProductRead(ProductCreate):
    id: int

    class Config:
        from_attributes = True


class OrderCreate(BaseModel):
    user_id: int
    product_id: int
    quantity: int = 1


class OrderRead(BaseModel):
    id: int
    user_id: int
    product_id: int
    quantity: int
    total_price: float

    class Config:
        from_attributes = True
""",
    )

    _write(root / "routes" / "__init__.py", "")

    _write(
        root / "routes" / "users.py",
        """from fastapi import APIRouter, Depends, HTTPException
from sqlalchemy.orm import Session
import models, schemas
from database import get_db

router = APIRouter(prefix="/users", tags=["Users"])


@router.post("/", response_model=schemas.UserRead)
def create_user(data: schemas.UserCreate, db: Session = Depends(get_db)):
    existing = db.query(models.User).filter(models.User.email == data.email).first()
    if existing:
        raise HTTPException(status_code=400, detail="Email already exists")

    user = models.User(name=data.name, email=data.email)
    db.add(user)
    db.commit()
    db.refresh(user)
    return user


@router.get("/", response_model=list[schemas.UserRead])
def list_users(db: Session = Depends(get_db)):
    return db.query(models.User).all()


@router.get("/{user_id}", response_model=schemas.UserRead)
def get_user(user_id: int, db: Session = Depends(get_db)):
    user = db.query(models.User).filter(models.User.id == user_id).first()
    if not user:
        raise HTTPException(status_code=404, detail="User not found")
    return user


@router.put("/{user_id}", response_model=schemas.UserRead)
def update_user(user_id: int, data: schemas.UserUpdate, db: Session = Depends(get_db)):
    user = db.query(models.User).filter(models.User.id == user_id).first()
    if not user:
        raise HTTPException(status_code=404, detail="User not found")

    if data.name is not None:
        user.name = data.name
    if data.email is not None:
        user.email = data.email

    db.commit()
    db.refresh(user)
    return user


@router.delete("/{user_id}")
def delete_user(user_id: int, db: Session = Depends(get_db)):
    user = db.query(models.User).filter(models.User.id == user_id).first()
    if not user:
        raise HTTPException(status_code=404, detail="User not found")

    db.delete(user)
    db.commit()
    return {"status": "deleted", "id": user_id}
""",
    )

    _write(
        root / "routes" / "products.py",
        """from fastapi import APIRouter, Depends, HTTPException
from sqlalchemy.orm import Session
import models, schemas
from database import get_db

router = APIRouter(prefix="/products", tags=["Products"])


@router.post("/", response_model=schemas.ProductRead)
def create_product(data: schemas.ProductCreate, db: Session = Depends(get_db)):
    product = models.Product(**data.model_dump())
    db.add(product)
    db.commit()
    db.refresh(product)
    return product


@router.get("/", response_model=list[schemas.ProductRead])
def list_products(db: Session = Depends(get_db)):
    return db.query(models.Product).all()


@router.get("/{product_id}", response_model=schemas.ProductRead)
def get_product(product_id: int, db: Session = Depends(get_db)):
    product = db.query(models.Product).filter(models.Product.id == product_id).first()
    if not product:
        raise HTTPException(status_code=404, detail="Product not found")
    return product


@router.put("/{product_id}", response_model=schemas.ProductRead)
def update_product(product_id: int, data: schemas.ProductUpdate, db: Session = Depends(get_db)):
    product = db.query(models.Product).filter(models.Product.id == product_id).first()
    if not product:
        raise HTTPException(status_code=404, detail="Product not found")

    for key, value in data.model_dump(exclude_unset=True).items():
        setattr(product, key, value)

    db.commit()
    db.refresh(product)
    return product


@router.delete("/{product_id}")
def delete_product(product_id: int, db: Session = Depends(get_db)):
    product = db.query(models.Product).filter(models.Product.id == product_id).first()
    if not product:
        raise HTTPException(status_code=404, detail="Product not found")

    db.delete(product)
    db.commit()
    return {"status": "deleted", "id": product_id}
""",
    )

    _write(
        root / "routes" / "orders.py",
        """from fastapi import APIRouter, Depends, HTTPException
from sqlalchemy.orm import Session
import models, schemas
from database import get_db

router = APIRouter(prefix="/orders", tags=["Orders"])


@router.post("/", response_model=schemas.OrderRead)
def create_order(data: schemas.OrderCreate, db: Session = Depends(get_db)):
    user = db.query(models.User).filter(models.User.id == data.user_id).first()
    if not user:
        raise HTTPException(status_code=404, detail="User not found")

    product = db.query(models.Product).filter(models.Product.id == data.product_id).first()
    if not product:
        raise HTTPException(status_code=404, detail="Product not found")

    if product.stock < data.quantity:
        raise HTTPException(status_code=400, detail="Not enough stock")

    total_price = product.price * data.quantity

    order = models.Order(
        user_id=data.user_id,
        product_id=data.product_id,
        quantity=data.quantity,
        total_price=total_price,
    )

    product.stock -= data.quantity

    db.add(order)
    db.commit()
    db.refresh(order)
    return order


@router.get("/", response_model=list[schemas.OrderRead])
def list_orders(db: Session = Depends(get_db)):
    return db.query(models.Order).all()


@router.get("/{order_id}", response_model=schemas.OrderRead)
def get_order(order_id: int, db: Session = Depends(get_db)):
    order = db.query(models.Order).filter(models.Order.id == order_id).first()
    if not order:
        raise HTTPException(status_code=404, detail="Order not found")
    return order


@router.delete("/{order_id}")
def delete_order(order_id: int, db: Session = Depends(get_db)):
    order = db.query(models.Order).filter(models.Order.id == order_id).first()
    if not order:
        raise HTTPException(status_code=404, detail="Order not found")

    db.delete(order)
    db.commit()
    return {"status": "deleted", "id": order_id}
""",
    )

    _write(
        root / "main.py",
        f"""from fastapi import FastAPI
import uvicorn
from database import Base, engine
from routes import users, products, orders

Base.metadata.create_all(bind=engine)

app = FastAPI(title="{name.title()} Ecommerce API")

app.include_router(users.router)
app.include_router(products.router)
app.include_router(orders.router)


@app.get("/")
def home():
    return {{
        "message": "{name} ecommerce API running",
        "docs": "http://127.0.0.1:9400/docs"
    }}


if __name__ == "__main__":
    uvicorn.run(app, host="127.0.0.1", port=9400)
""",
    )

    files = [
        str(p.relative_to(root)).replace("\\", "/")
        for p in root.rglob("*")
        if p.is_file()
    ]

    rel = root.relative_to(PROJECT_ROOT)

    return f"""Ecommerce API project created: {rel}

Files:
{chr(10).join("- " + file for file in files)}

Run:

cd {rel}
pip install -r requirements.txt
python main.py

Docs:

http://127.0.0.1:9400/docs
"""


def _project_plan(raw: str) -> str:
    """Return a structured project plan. No files are created."""
    q = raw.lower()
    description = re.sub(r"^(build project:|create project:)\s*", "", raw, flags=re.IGNORECASE).strip()
    name = _project_name(raw)

    # ── Tech-stack detection ─────────────────────────────────────────────────
    has_react   = bool(re.search(r"\breact\b", q))
    has_vue     = bool(re.search(r"\bvue\b", q))
    has_nextjs  = bool(re.search(r"\bnext\.?js\b", q))
    has_fastapi = bool(re.search(r"\bfastapi\b", q))
    has_django  = bool(re.search(r"\bdjango\b", q))
    has_flask   = bool(re.search(r"\bflask\b", q))
    has_node    = bool(re.search(r"\bnode\.?js\b|\bexpress\b", q))
    has_db      = bool(re.search(r"\bsqlite\b|\bdatabase\b|\bdb\b|\bsql\b", q))

    frontend = "Next.js" if has_nextjs else "React" if has_react else "Vue" if has_vue else None
    backend  = ("FastAPI" if has_fastapi
                else "Django" if has_django
                else "Flask"  if has_flask
                else "Node.js / Express" if has_node
                else "FastAPI")  # default

    stack_parts = ([frontend] if frontend else []) + [backend] + (["SQLite"] if has_db else [])
    tech_stack  = " + ".join(stack_parts)

    # ── Folder structure + files ─────────────────────────────────────────────
    if frontend:
        # Fullstack layout
        if backend in ("FastAPI", "Flask", "Django"):
            be_run = (
                "cd backend\npip install -r requirements.txt\npython main.py"
                if backend != "Django"
                else "cd backend\npip install -r requirements.txt\npython manage.py runserver"
            )
            fe_run = (
                "cd frontend\nnpm install\nnpm run dev"
                if frontend in ("React", "Next.js")
                else "cd frontend\nnpm install\nnpm run serve"
            )
            folder_tree = (
                f"{name}/\n"
                f"├── backend/\n"
                f"│   ├── main.py\n"
                f"│   ├── requirements.txt\n"
                f"│   └── README.md\n"
                f"└── frontend/\n"
                f"    ├── src/\n"
                f"    │   ├── App.{'tsx' if frontend == 'React' else 'vue'}\n"
                f"    │   └── main.{'tsx' if frontend == 'React' else 'js'}\n"
                f"    ├── index.html\n"
                f"    └── package.json"
            )
            files_list = (
                f"- backend/main.py          {backend} app with CORS + REST endpoints\n"
                f"- backend/requirements.txt\n"
                f"- frontend/src/App.{'tsx' if frontend == 'React' else 'vue'}    {frontend} main component\n"
                f"- frontend/index.html\n"
                f"- frontend/package.json"
            )
            run_commands = f"Backend:\n  {be_run.replace(chr(10), chr(10) + '  ')}\n\nFrontend:\n  {fe_run.replace(chr(10), chr(10) + '  ')}"
        else:
            # Node/Express + React
            folder_tree = (
                f"{name}/\n"
                f"├── server/\n"
                f"│   ├── index.js\n"
                f"│   └── package.json\n"
                f"└── client/\n"
                f"    ├── src/App.jsx\n"
                f"    └── package.json"
            )
            files_list = (
                "- server/index.js       Express REST API\n"
                "- server/package.json\n"
                "- client/src/App.jsx    React main component\n"
                "- client/package.json"
            )
            run_commands = "Server:\n  cd server\n  npm install\n  node index.js\n\nClient:\n  cd client\n  npm install\n  npm run dev"
    else:
        # Backend-only
        folder_tree = (
            f"{name}/\n"
            f"├── main.py\n"
            f"├── requirements.txt\n"
            f"└── README.md"
        )
        files_list = (
            "- main.py           FastAPI app with CRUD endpoints\n"
            "- requirements.txt\n"
            "- README.md"
        )
        run_commands = "cd {name}\npip install -r requirements.txt\npython main.py"

    return (
        f"Project Plan: {description or name}\n"
        f"{'=' * 48}\n\n"
        f"Name:       {name}\n"
        f"Tech Stack: {tech_stack}\n\n"
        f"Folder Structure:\n{folder_tree}\n\n"
        f"Files to Create:\n{files_list}\n\n"
        f"Run Commands:\n{run_commands}\n\n"
        f"Next Step:\n"
        f"  Type the command below to generate all files:\n\n"
        f"  create project: {description or name}\n"
    )


def build_project(name: str) -> str:
    try:
        raw = name.strip()
        lowered = raw.lower()

        # "build project:" → return a plan only, never create files.
        if lowered.startswith("build project:"):
            return _project_plan(raw)

        clean_name = _project_name(raw)

        root = safe_path(f"projects/{clean_name}")
        root.mkdir(parents=True, exist_ok=True)

        if "build api:" in lowered or "create api:" in lowered:
            return _ecommerce_api_project(root, clean_name)

        if "blog" in lowered:
            return _blog_api_project(root, clean_name)

        if "dashboard" in lowered or "admin" in lowered:
            return _dashboard_project(root, clean_name)

        if "cli" in lowered or "command line" in lowered:
            return _cli_project(root, clean_name)

        if (
            "fullstack" in lowered
            or "full stack" in lowered
            or "frontend" in lowered
            or "advanced" in lowered
            or "with database" in lowered
        ):
            return _todo_fullstack_project(root, clean_name)

        return _basic_fastapi_project(root, clean_name)

    except Exception as e:
        return str(e)


def system_info(_: str = "") -> str:
    from app.core.system_detector import live_ram_mb, detect_system
    avail, total = live_ram_mb()
    p = detect_system()
    return (
        f"OS:        {p.os} {p.arch}\n"
        f"CPU:       {p.cpu_cores_physical} physical / {p.cpu_cores_logical} logical cores\n"
        f"RAM:       {avail} MB available / {total} MB total\n"
        f"Tier:      {p.tier.upper()}\n"
        f"AVX2:      {'yes' if p.has_avx2 else 'no'}\n"
        f"CUDA:      {'yes' if p.has_cuda else 'no'}\n"
        f"Disk free: {p.disk_free_gb} GB"
    )


def explain_code(raw: str) -> str:
    code = re.sub(r"(?i)^explain code:\s*", "", raw).strip()
    q = code.lower()
    lines = code.strip().splitlines()

    if re.search(r"\bdef \b|import \w|print\(", code):
        lang = "Python"
    elif re.search(r"\bfunction\b|\bconst\b|\blet\b|\bconsole\.log\b", code):
        lang = "JavaScript/TypeScript"
    elif re.search(r"<[a-z][\w]*", code):
        lang = "HTML/JSX"
    else:
        lang = "Code"

    what = []
    funcs = re.findall(r"def (\w+)\s*\(", code)
    if funcs:
        what.append(f"Defines function(s): {', '.join(funcs)}")
    for cls in re.findall(r"class (\w+)", code):
        what.append(f"Defines class: {cls}")
    if re.search(r"\breturn\b", code):
        what.append("Returns a computed value")
    if re.search(r"\bfor\b|\bwhile\b", code):
        what.append("Iterates with a loop")
    if re.search(r"\bif\b", code):
        what.append("Contains conditional logic")
    imports = re.findall(r"import (\w+)|from (\w+)", code)
    if imports:
        flat = [a or b for a, b in imports]
        what.append(f"Imports: {', '.join(flat[:4])}")
    if not what:
        what.append(f"Block of {len(lines)} line(s) of {lang}")

    tips = []
    if funcs and '"""' not in code and "'''" not in code:
        tips.append("Add docstrings to document what each function does")
    if re.search(r"except\s*:", code):
        tips.append("Replace bare `except:` with specific exception types")
    if len(lines) > 30:
        tips.append("Consider splitting into smaller, focused functions")
    if re.search(r"def \w+\(.*\)\s*:", code) and "->" not in code:
        tips.append("Add type hints for better readability and IDE support")
    if not tips:
        tips.append("Looks clean — consider adding comments for complex logic")

    out = f"🔍 Summary\n{lang} code"
    if funcs:
        out += f" — defines {', '.join(funcs)}"
    out += f" ({len(lines)} line{'s' if len(lines) != 1 else ''})\n"

    out += "\n⚙️ How it works\n"
    for w in what:
        out += f"  • {w}\n"

    out += "\n💡 Suggestions\n"
    for t in tips:
        out += f"  • {t}\n"
    return out


def fix_error(raw: str) -> str:
    err = re.sub(r"(?i)^fix error:\s*", "", raw).strip()
    e = err.lower()

    def _fmt(problem: str, cause: str, fix: str, example: str) -> str:
        return (
            f"❌ Problem\n  {problem}\n\n"
            f"🔎 Cause\n  {cause}\n\n"
            f"✅ Fix\n{fix}\n\n"
            f"🧪 Example\n{example}"
        )

    if "no module named" in e or "modulenotfounderror" in e:
        m = re.search(r"no module named ['\"]?([\w\.]+)['\"]?", err, re.IGNORECASE)
        pkg = m.group(1) if m else "the-package"
        return _fmt(
            f"ModuleNotFoundError: No module named '{pkg}'",
            f"'{pkg}' is not installed in the current Python environment.",
            f"```bash\npip install {pkg}\n```",
            f"```bash\n# activate venv first (if using one)\nvenv\\Scripts\\activate   # Windows\nsource venv/bin/activate # Mac/Linux\npip install {pkg}\n```",
        )

    if "syntaxerror" in e:
        return _fmt(
            "SyntaxError: invalid syntax",
            "Missing `:`, unmatched brackets, or inconsistent indentation.",
            "  1. Find the line number in the traceback\n"
            "  2. Check for missing `:` after `if / for / def / class`\n"
            "  3. Check for unmatched `()`, `[]`, `{}`\n"
            "  4. Use 4 spaces per indent level — no tabs",
            "```python\ndef add(a, b):  # colon required\n    return a + b\n```",
        )

    if "typeerror" in e:
        return _fmt(
            "TypeError: unsupported operand or wrong argument type",
            "A value of the wrong type was passed to a function or operator.",
            "  1. Check variable types with `type(x)`\n"
            "  2. Convert as needed: `str()`, `int()`, `float()`",
            "```python\nresult = int(value) + 1  # convert before adding\n```",
        )

    if "nameerror" in e or "is not defined" in e:
        return _fmt(
            "NameError: name is not defined",
            "Variable or function used before it was defined, or it was misspelled.",
            "  1. Check spelling carefully\n"
            "  2. Define the variable before using it\n"
            "  3. Variables inside functions are local — check scope",
            "```python\nname = 'Alice'  # define first\nprint(name)     # then use\n```",
        )

    if "attributeerror" in e:
        return _fmt(
            "AttributeError: object has no attribute",
            "Calling a method or property that doesn't exist on that type.",
            "  1. `print(type(obj))` to inspect the type\n"
            "  2. `print(dir(obj))` to list valid attributes\n"
            "  3. Check for typos in the attribute name",
            "```python\nprint(type(my_var))  # check what it actually is\nprint(dir(my_var))   # list available attributes\n```",
        )

    if "indentationerror" in e:
        return _fmt(
            "IndentationError: unexpected indent",
            "Mixed tabs and spaces, or wrong indent level.",
            "  Use exactly 4 spaces per level — no tabs.\n"
            "  In VS Code: View → Render Whitespace to spot mixed indent.",
            "```python\ndef greet():\n    print('hello')  # 4 spaces, not a tab\n```",
        )

    if "connection refused" in e or "connectionerror" in e:
        return _fmt(
            "ConnectionRefusedError: connection refused",
            "The backend server is not running, or the port is wrong.",
            "```bash\nuvicorn main:app --reload --port 8000\n```",
            "Confirm the URL matches: http://127.0.0.1:8000",
        )

    if "cors" in e:
        return _fmt(
            "CORS error: request blocked by browser",
            "Frontend origin is not allowed by the backend's CORS policy.",
            "Add this to your FastAPI app:\n"
            "```python\nfrom fastapi.middleware.cors import CORSMiddleware\n\napp.add_middleware(\n    CORSMiddleware,\n    allow_origins=['*'],\n    allow_methods=['*'],\n    allow_headers=['*'],\n)\n```",
            "Place `add_middleware` right after `app = FastAPI()`.",
        )

    return (
        f"❌ Problem\n  {err}\n\n"
        "🔎 Cause\n  Unknown — read the full traceback for details.\n\n"
        "✅ Fix\n"
        "  1. Read the full traceback — the real error is the last line\n"
        "  2. Search the exact message on Stack Overflow\n"
        "  3. Reinstall dependencies: `pip install -r requirements.txt`\n"
        "  4. Check Python version: `python --version`\n\n"
        "🧪 Example\n  Paste the exact traceback for a more specific fix."
    )


def _write_blog_project(root: Path, name: str) -> str:
    be, src = root / "backend", root / "frontend" / "src"

    _write(be / "main.py", f"""\
from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel
import uvicorn

app = FastAPI(title="{name.replace('-', ' ').title()} API")
app.add_middleware(CORSMiddleware, allow_origins=["*"], allow_credentials=True,
                   allow_methods=["*"], allow_headers=["*"])

posts = []

class PostCreate(BaseModel):
    title: str
    content: str
    author: str = "Anonymous"

@app.get("/")
def home(): return {{"message": "{name} API running"}}

@app.get("/posts")
def list_posts(): return {{"posts": posts}}

@app.post("/posts")
def create_post(data: PostCreate):
    post = {{"id": len(posts)+1, "title": data.title,
             "content": data.content, "author": data.author}}
    posts.append(post); return post

@app.get("/posts/{{post_id}}")
def get_post(post_id: int):
    for p in posts:
        if p["id"] == post_id: return p
    raise HTTPException(404, "Not found")

@app.delete("/posts/{{post_id}}")
def delete_post(post_id: int):
    global posts
    posts = [p for p in posts if p["id"] != post_id]
    return {{"status": "deleted"}}

if __name__ == "__main__": uvicorn.run(app, host="127.0.0.1", port=9100)
""")
    _write(be / "requirements.txt", "fastapi\nuvicorn\npydantic\n")
    _write(be / "README.md", f"# {name}\n\nRun: uvicorn main:app --reload\nDocs: http://127.0.0.1:9100/docs\n")

    _write((root / "frontend") / "package.json", '{"name":"blog-app","version":"1.0.0","scripts":{"dev":"vite","build":"tsc && vite build"},"dependencies":{"react":"^18.2.0","react-dom":"^18.2.0"},"devDependencies":{"@types/react":"^18.2.0","@types/react-dom":"^18.2.0","@vitejs/plugin-react":"^4.0.0","typescript":"^5.0.0","vite":"^4.4.0"}}\n')
    _write((root / "frontend") / "index.html", '<!DOCTYPE html>\n<html lang="en"><head><meta charset="UTF-8"/><title>Blog</title></head><body><div id="root"></div><script type="module" src="/src/main.tsx"></script></body></html>\n')
    _write(src / "main.tsx", "import React from 'react'\nimport ReactDOM from 'react-dom/client'\nimport App from './App'\nReactDOM.createRoot(document.getElementById('root')!).render(<React.StrictMode><App/></React.StrictMode>)\n")
    _write(src / "App.tsx", """\
import React, { useEffect, useState } from 'react'
const API = 'http://127.0.0.1:9100'
interface Post { id: number; title: string; content: string; author: string }
export default function App() {
  const [posts, setPosts] = useState<Post[]>([])
  const [title, setTitle] = useState(''); const [content, setContent] = useState('')
  useEffect(() => { load() }, [])
  async function load() { const r = await fetch(API+'/posts'); const d = await r.json(); setPosts(d.posts) }
  async function add() {
    if (!title.trim()) return
    await fetch(API+'/posts', { method:'POST', headers:{'Content-Type':'application/json'}, body: JSON.stringify({title, content, author:'Me'}) })
    setTitle(''); setContent(''); load()
  }
  return (
    <div style={{fontFamily:'Arial',maxWidth:720,margin:'40px auto',padding:'0 20px'}}>
      <h1>Blog</h1>
      <div style={{marginBottom:24,padding:16,background:'#f9fafb',borderRadius:8}}>
        <input value={title} onChange={e=>setTitle(e.target.value)} placeholder="Post title" style={{display:'block',width:'100%',marginBottom:8,padding:8,border:'1px solid #ddd',borderRadius:6}}/>
        <textarea value={content} onChange={e=>setContent(e.target.value)} placeholder="Content..." rows={3} style={{display:'block',width:'100%',marginBottom:8,padding:8,border:'1px solid #ddd',borderRadius:6}}/>
        <button onClick={add} style={{padding:'8px 16px',background:'#4f46e5',color:'white',border:'none',borderRadius:6,cursor:'pointer'}}>Publish</button>
      </div>
      {posts.map(p=>(
        <div key={p.id} style={{marginBottom:16,padding:16,background:'white',border:'1px solid #e5e7eb',borderRadius:8}}>
          <h2 style={{margin:'0 0 4px'}}>{p.title}</h2>
          <div style={{fontSize:12,color:'#9ca3af',marginBottom:8}}>by {p.author}</div>
          <p style={{margin:0}}>{p.content}</p>
        </div>
      ))}
    </div>
  )
}
""")
    rel = f"backend/generated_projects/{name}"
    return f"[PROJECT WRITTEN]\nLocation: {rel}\n\nRun commands:\n  cd {rel}/backend\n  pip install -r requirements.txt\n  uvicorn main:app --reload\n\n  cd {rel}/frontend\n  npm install\n  npm run dev\n"


def _write_notes_project(root: Path, name: str) -> str:
    be, src = root / "backend", root / "frontend" / "src"

    _write(be / "main.py", f"""\
from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel
import uvicorn

app = FastAPI(title="{name.replace('-', ' ').title()} API")
app.add_middleware(CORSMiddleware, allow_origins=["*"], allow_credentials=True,
                   allow_methods=["*"], allow_headers=["*"])

notes = []

class NoteCreate(BaseModel):
    title: str
    content: str

@app.get("/"); def home(): return {{"message": "{name} running"}}
@app.get("/notes"); def list_notes(): return {{"notes": notes}}
@app.post("/notes")
def create_note(data: NoteCreate):
    note = {{"id": len(notes)+1, "title": data.title, "content": data.content}}
    notes.append(note); return note

@app.put("/notes/{{note_id}}")
def update_note(note_id: int, data: NoteCreate):
    for n in notes:
        if n["id"] == note_id: n.update({{"title": data.title, "content": data.content}}); return n
    raise HTTPException(404, "Not found")

@app.delete("/notes/{{note_id}}")
def delete_note(note_id: int):
    global notes; notes = [n for n in notes if n["id"] != note_id]; return {{"status": "deleted"}}

if __name__ == "__main__": uvicorn.run(app, host="127.0.0.1", port=9100)
""")
    _write(be / "requirements.txt", "fastapi\nuvicorn\npydantic\n")
    _write(be / "README.md", f"# {name}\n\nRun: uvicorn main:app --reload\nDocs: http://127.0.0.1:9100/docs\n")

    _write((root / "frontend") / "package.json", '{"name":"notes-app","version":"1.0.0","scripts":{"dev":"vite","build":"tsc && vite build"},"dependencies":{"react":"^18.2.0","react-dom":"^18.2.0"},"devDependencies":{"@types/react":"^18.2.0","@types/react-dom":"^18.2.0","@vitejs/plugin-react":"^4.0.0","typescript":"^5.0.0","vite":"^4.4.0"}}\n')
    _write((root / "frontend") / "index.html", '<!DOCTYPE html>\n<html lang="en"><head><meta charset="UTF-8"/><title>Notes</title></head><body><div id="root"></div><script type="module" src="/src/main.tsx"></script></body></html>\n')
    _write(src / "main.tsx", "import React from 'react'\nimport ReactDOM from 'react-dom/client'\nimport App from './App'\nReactDOM.createRoot(document.getElementById('root')!).render(<React.StrictMode><App/></React.StrictMode>)\n")
    _write(src / "App.tsx", """\
import React, { useEffect, useState } from 'react'
const API = 'http://127.0.0.1:9100'
interface Note { id: number; title: string; content: string }
export default function App() {
  const [notes, setNotes] = useState<Note[]>([])
  const [title, setTitle] = useState(''); const [content, setContent] = useState(''); const [sel, setSel] = useState<Note|null>(null)
  useEffect(() => { load() }, [])
  async function load() { const r = await fetch(API+'/notes'); const d = await r.json(); setNotes(d.notes) }
  async function save() {
    if (!title.trim()) return
    await fetch(API+'/notes', { method:'POST', headers:{'Content-Type':'application/json'}, body: JSON.stringify({title, content}) })
    setTitle(''); setContent(''); load()
  }
  return (
    <div style={{fontFamily:'Arial',display:'flex',height:'100vh'}}>
      <aside style={{width:240,borderRight:'1px solid #e5e7eb',padding:16,overflowY:'auto'}}>
        <h2 style={{margin:'0 0 12px'}}>Notes</h2>
        {notes.map(n=>(
          <div key={n.id} onClick={()=>setSel(n)} style={{padding:8,marginBottom:4,background:sel?.id===n.id?'#ede9fe':'#f9fafb',borderRadius:6,cursor:'pointer'}}>
            <div style={{fontWeight:600,fontSize:14}}>{n.title}</div>
          </div>
        ))}
      </aside>
      <main style={{flex:1,padding:24}}>
        {sel ? (
          <div><h1>{sel.title}</h1><p>{sel.content}</p></div>
        ) : (
          <div>
            <h2>New Note</h2>
            <input value={title} onChange={e=>setTitle(e.target.value)} placeholder="Title" style={{display:'block',width:'100%',marginBottom:8,padding:8,border:'1px solid #ddd',borderRadius:6}}/>
            <textarea value={content} onChange={e=>setContent(e.target.value)} rows={6} placeholder="Write your note..." style={{display:'block',width:'100%',marginBottom:8,padding:8,border:'1px solid #ddd',borderRadius:6}}/>
            <button onClick={save} style={{padding:'8px 16px',background:'#4f46e5',color:'white',border:'none',borderRadius:6,cursor:'pointer'}}>Save</button>
          </div>
        )}
      </main>
    </div>
  )
}
""")
    rel = f"backend/generated_projects/{name}"
    return f"[PROJECT WRITTEN]\nLocation: {rel}\n\nRun commands:\n  cd {rel}/backend\n  pip install -r requirements.txt\n  uvicorn main:app --reload\n\n  cd {rel}/frontend\n  npm install\n  npm run dev\n"


def _write_ecommerce_project(root: Path, name: str) -> str:
    be, src = root / "backend", root / "frontend" / "src"

    _write(be / "main.py", f"""\
from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel
import uvicorn

app = FastAPI(title="{name.replace('-', ' ').title()} Shop API")
app.add_middleware(CORSMiddleware, allow_origins=["*"], allow_credentials=True,
                   allow_methods=["*"], allow_headers=["*"])

products = [
    {{"id": 1, "name": "T-Shirt", "price": 19.99, "stock": 50}},
    {{"id": 2, "name": "Hoodie", "price": 39.99, "stock": 30}},
    {{"id": 3, "name": "Cap", "price": 14.99, "stock": 100}},
]
cart: list[dict] = []

class ProductCreate(BaseModel):
    name: str
    price: float
    stock: int = 0

@app.get("/")
def home(): return {{"message": "{name} shop API running"}}

@app.get("/products")
def list_products(): return {{"products": products}}

@app.post("/products")
def add_product(data: ProductCreate):
    p = {{"id": len(products)+1, "name": data.name, "price": data.price, "stock": data.stock}}
    products.append(p); return p

@app.get("/products/{{product_id}}")
def get_product(product_id: int):
    for p in products:
        if p["id"] == product_id: return p
    raise HTTPException(404, "Product not found")

@app.delete("/products/{{product_id}}")
def delete_product(product_id: int):
    global products
    products = [p for p in products if p["id"] != product_id]
    return {{"status": "deleted"}}

@app.get("/cart")
def get_cart(): return {{"cart": cart, "total": sum(i["price"]*i["qty"] for i in cart)}}

@app.post("/cart/{{product_id}}")
def add_to_cart(product_id: int, qty: int = 1):
    for p in products:
        if p["id"] == product_id:
            for item in cart:
                if item["product_id"] == product_id:
                    item["qty"] += qty; return {{"cart": cart}}
            cart.append({{"product_id": product_id, "name": p["name"],
                          "price": p["price"], "qty": qty}})
            return {{"cart": cart}}
    raise HTTPException(404, "Product not found")

@app.delete("/cart/{{product_id}}")
def remove_from_cart(product_id: int):
    global cart; cart = [i for i in cart if i["product_id"] != product_id]
    return {{"cart": cart}}

if __name__ == "__main__": uvicorn.run(app, host="127.0.0.1", port=9100)
""")
    _write(be / "requirements.txt", "fastapi\nuvicorn\npydantic\n")
    _write(be / "README.md", f"# {name}\n\nRun: uvicorn main:app --reload\nDocs: http://127.0.0.1:9100/docs\n")

    _write((root / "frontend") / "package.json", '{"name":"shop-app","version":"1.0.0","scripts":{"dev":"vite","build":"tsc && vite build"},"dependencies":{"react":"^18.2.0","react-dom":"^18.2.0"},"devDependencies":{"@types/react":"^18.2.0","@types/react-dom":"^18.2.0","@vitejs/plugin-react":"^4.0.0","typescript":"^5.0.0","vite":"^4.4.0"}}\n')
    _write((root / "frontend") / "index.html", '<!DOCTYPE html>\n<html lang="en"><head><meta charset="UTF-8"/><title>Shop</title></head><body><div id="root"></div><script type="module" src="/src/main.tsx"></script></body></html>\n')
    _write(src / "main.tsx", "import React from 'react'\nimport ReactDOM from 'react-dom/client'\nimport App from './App'\nReactDOM.createRoot(document.getElementById('root')!).render(<React.StrictMode><App/></React.StrictMode>)\n")
    _write(src / "App.tsx", """\
import React, { useEffect, useState } from 'react'
const API = 'http://127.0.0.1:9100'
interface Product { id: number; name: string; price: number; stock: number }
interface CartItem { product_id: number; name: string; price: number; qty: number }
export default function App() {
  const [products, setProducts] = useState<Product[]>([])
  const [cart, setCart] = useState<CartItem[]>([])
  const [total, setTotal] = useState(0)
  const [tab, setTab] = useState<'shop'|'cart'>('shop')
  useEffect(() => { loadProducts(); loadCart() }, [])
  async function loadProducts() { const r = await fetch(API+'/products'); const d = await r.json(); setProducts(d.products) }
  async function loadCart() { const r = await fetch(API+'/cart'); const d = await r.json(); setCart(d.cart); setTotal(d.total) }
  async function addToCart(id: number) { await fetch(API+'/cart/'+id, {method:'POST'}); loadCart() }
  async function removeFromCart(id: number) { await fetch(API+'/cart/'+id, {method:'DELETE'}); loadCart() }
  const btn = (active: boolean) => ({padding:'8px 20px',border:'none',borderRadius:6,cursor:'pointer',background:active?'#4f46e5':'#e5e7eb',color:active?'white':'#111'})
  return (
    <div style={{fontFamily:'Arial',maxWidth:800,margin:'40px auto',padding:'0 20px'}}>
      <h1 style={{marginBottom:4}}>Shop</h1>
      <div style={{display:'flex',gap:8,marginBottom:20}}>
        <button style={btn(tab==='shop')} onClick={()=>setTab('shop')}>Products</button>
        <button style={btn(tab==='cart')} onClick={()=>setTab('cart')}>Cart ({cart.length})</button>
      </div>
      {tab==='shop' && (
        <div style={{display:'grid',gridTemplateColumns:'repeat(auto-fill,minmax(200px,1fr))',gap:16}}>
          {products.map(p=>(
            <div key={p.id} style={{padding:16,background:'#f9fafb',borderRadius:8,border:'1px solid #e5e7eb'}}>
              <div style={{fontWeight:600,fontSize:16,marginBottom:4}}>{p.name}</div>
              <div style={{color:'#4f46e5',fontWeight:700,marginBottom:8}}>${p.price.toFixed(2)}</div>
              <div style={{fontSize:12,color:'#9ca3af',marginBottom:10}}>Stock: {p.stock}</div>
              <button onClick={()=>addToCart(p.id)} style={{width:'100%',padding:'8px 0',background:'#4f46e5',color:'white',border:'none',borderRadius:6,cursor:'pointer'}}>Add to Cart</button>
            </div>
          ))}
        </div>
      )}
      {tab==='cart' && (
        <div>
          {cart.length===0 && <p style={{color:'#9ca3af'}}>Cart is empty.</p>}
          {cart.map(item=>(
            <div key={item.product_id} style={{display:'flex',justifyContent:'space-between',alignItems:'center',padding:12,marginBottom:8,background:'#f9fafb',borderRadius:8}}>
              <span>{item.name} x{item.qty}</span>
              <span style={{fontWeight:700}}>${(item.price*item.qty).toFixed(2)}</span>
              <button onClick={()=>removeFromCart(item.product_id)} style={{background:'#ef4444',color:'white',border:'none',borderRadius:4,padding:'4px 10px',cursor:'pointer'}}>Remove</button>
            </div>
          ))}
          {cart.length>0 && <div style={{textAlign:'right',fontWeight:700,fontSize:18,marginTop:12}}>Total: ${total.toFixed(2)}</div>}
        </div>
      )}
    </div>
  )
}
""")
    rel = f"backend/generated_projects/{name}"
    return f"[PROJECT WRITTEN]\nLocation: {rel}\n\nRun commands:\n  cd {rel}/backend\n  pip install -r requirements.txt\n  uvicorn main:app --reload\n\n  cd {rel}/frontend\n  npm install\n  npm run dev\n"


def _gen_project_name(raw: str) -> str:
    q = raw.strip()
    for prefix in ("auto file write", "create project:", "build project:"):
        if q.lower().startswith(prefix):
            q = q[len(prefix):].strip()
            break
    for kw in ("react", "fastapi", "vue", "django", "flask", "nodejs", "node.js",
               "nextjs", "next.js", "typescript", "javascript", "with", r"\+"):
        q = re.sub(r"(?i)\b" + re.escape(kw.lstrip(r"\\")) + r"\b", "", q)
    q = re.sub(r"\s+", "-", q.strip()).strip("-")
    q = re.sub(r"-+", "-", re.sub(r"[^\w\-]", "", q))
    return q.lower() or "my-project"


def auto_file_write(raw: str) -> str:
    """Write a React + FastAPI project scaffold to generated_projects/."""
    try:
        name = _gen_project_name(raw)
        root = (GENERATED_ROOT / name).resolve()
        if not str(root).startswith(str(GENERATED_ROOT.resolve())):
            return "Error: path escape denied."
        GENERATED_ROOT.mkdir(parents=True, exist_ok=True)

        q = raw.lower()
        if re.search(r"\bblog\b", q):
            result = _write_blog_project(root, name)
            _register_if_ok(name, result)
            return result
        if re.search(r"\bnotes?\b", q):
            result = _write_notes_project(root, name)
            _register_if_ok(name, result)
            return result
        if re.search(r"\becommerce\b|\bshop\b|\bstore\b|\bcart\b", q):
            result = _write_ecommerce_project(root, name)
            _register_if_ok(name, result)
            return result

        be = root / "backend"
        fe = root / "frontend"
        src = fe / "src"

        _write(be / "main.py", f"""\
from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
import uvicorn

app = FastAPI(title="{name.replace('-', ' ').title()} API")

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

todos = []

@app.get("/")
def home():
    return {{"message": "{name} API running"}}

@app.get("/todos")
def list_todos():
    return {{"todos": todos}}

@app.post("/todos")
def create_todo(title: str):
    todo = {{"id": len(todos) + 1, "title": title, "done": False}}
    todos.append(todo)
    return todo

@app.put("/todos/{{todo_id}}")
def toggle_todo(todo_id: int):
    for todo in todos:
        if todo["id"] == todo_id:
            todo["done"] = not todo["done"]
            return todo
    return {{"error": "Not found"}}

@app.delete("/todos/{{todo_id}}")
def delete_todo(todo_id: int):
    global todos
    todos = [t for t in todos if t["id"] != todo_id]
    return {{"status": "deleted"}}

if __name__ == "__main__":
    uvicorn.run(app, host="127.0.0.1", port=9100)
""")

        _write(be / "requirements.txt", "fastapi\nuvicorn\n")

        _write(be / "README.md", f"""\
# {name.replace('-', ' ').title()}

Generated by IntelliYash Auto File Writer.

## Run backend

cd backend
pip install -r requirements.txt
uvicorn main:app --reload

API: http://127.0.0.1:9100
Docs: http://127.0.0.1:9100/docs
""")

        _write(fe / "package.json", """\
{
  "name": "todo-app",
  "version": "1.0.0",
  "scripts": {
    "dev": "vite",
    "build": "tsc && vite build",
    "preview": "vite preview"
  },
  "dependencies": {
    "react": "^18.2.0",
    "react-dom": "^18.2.0"
  },
  "devDependencies": {
    "@types/react": "^18.2.0",
    "@types/react-dom": "^18.2.0",
    "@vitejs/plugin-react": "^4.0.0",
    "typescript": "^5.0.0",
    "vite": "^4.4.0"
  }
}
""")

        _write(fe / "index.html", """\
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>Todo App</title>
</head>
<body>
  <div id="root"></div>
  <script type="module" src="/src/main.tsx"></script>
</body>
</html>
""")

        _write(src / "main.tsx", """\
import React from 'react'
import ReactDOM from 'react-dom/client'
import App from './App'

ReactDOM.createRoot(document.getElementById('root')!).render(
  <React.StrictMode>
    <App />
  </React.StrictMode>
)
""")

        _write(src / "App.tsx", """\
import React, { useEffect, useState } from 'react'

const API = 'http://127.0.0.1:9100'

interface Todo { id: number; title: string; done: boolean }

export default function App() {
  const [todos, setTodos] = useState<Todo[]>([])
  const [input, setInput] = useState('')

  useEffect(() => { load() }, [])

  async function load() {
    const res = await fetch(API + '/todos')
    const data = await res.json()
    setTodos(data.todos)
  }

  async function add() {
    if (!input.trim()) return
    await fetch(API + '/todos?title=' + encodeURIComponent(input), { method: 'POST' })
    setInput(''); load()
  }

  async function toggle(id: number) {
    await fetch(API + '/todos/' + id, { method: 'PUT' }); load()
  }

  async function del(id: number) {
    await fetch(API + '/todos/' + id, { method: 'DELETE' }); load()
  }

  return (
    <div style={{ fontFamily: 'Arial', maxWidth: 600, margin: '40px auto', padding: '0 20px' }}>
      <h1>Todo App</h1>
      <div style={{ display: 'flex', gap: 8, marginBottom: 20 }}>
        <input
          value={input}
          onChange={e => setInput(e.target.value)}
          onKeyDown={e => e.key === 'Enter' && add()}
          placeholder="Add a todo..."
          style={{ flex: 1, padding: 8, border: '1px solid #ddd', borderRadius: 6 }}
        />
        <button onClick={add}
          style={{ padding: '8px 16px', background: '#4f46e5', color: 'white', border: 'none', borderRadius: 6, cursor: 'pointer' }}>
          Add
        </button>
      </div>
      <ul style={{ listStyle: 'none', padding: 0 }}>
        {todos.map(t => (
          <li key={t.id} style={{ display: 'flex', alignItems: 'center', gap: 8, padding: 10, marginBottom: 8, background: '#f9fafb', borderRadius: 8 }}>
            <span onClick={() => toggle(t.id)}
              style={{ flex: 1, cursor: 'pointer', textDecoration: t.done ? 'line-through' : 'none', opacity: t.done ? 0.5 : 1 }}>
              {t.title}
            </span>
            <button onClick={() => del(t.id)}
              style={{ background: '#ef4444', color: 'white', border: 'none', borderRadius: 4, padding: '4px 8px', cursor: 'pointer' }}>
              Delete
            </button>
          </li>
        ))}
      </ul>
    </div>
  )
}
""")

        rel = f"backend/generated_projects/{name}"
        result = (
            f"[PROJECT WRITTEN]\n"
            f"Location: {rel}\n\n"
            f"Run commands:\n"
            f"  cd {rel}/backend\n"
            f"  pip install -r requirements.txt\n"
            f"  uvicorn main:app --reload\n\n"
            f"  cd {rel}/frontend\n"
            f"  npm install\n"
            f"  npm run dev\n"
        )
        _register_if_ok(name, result)
        return result
    except Exception as exc:
        return f"Error writing project: {exc}"


def _register_if_ok(name: str, result: str) -> None:
    """Persist a successfully-written project to projects.json.

    Called after every auto_file_write branch.  Silently skipped on any
    error so the project write itself is never affected.
    """
    if result.startswith("Error"):
        return
    try:
        from app.services.project_store import register_project
        rel = f"backend/generated_projects/{name}"
        register_project({
            "name":         name,
            "path":         rel,
            "run_backend":  (
                f"cd {rel}/backend\n"
                "pip install -r requirements.txt\n"
                "uvicorn main:app --reload"
            ),
            "run_frontend": (
                f"cd {rel}/frontend\n"
                "npm install\n"
                "npm run dev"
            ),
        })
    except Exception:
        pass  # persistence is best-effort


TOOLS = {
    "python": run_python,
    "calc": calculator,
    "file": read_file,
    "write_file": write_file,
    "append_file": append_file,
    "builder": build_project,
    "api_generator": build_project,
    "auto_file_writer": auto_file_write,
    "system_info": system_info,
    "explain": explain_code,
    "fix_error": fix_error,
}