import io
import shutil
import zipfile
from pathlib import Path

from fastapi import APIRouter, HTTPException
from fastapi.responses import StreamingResponse

router = APIRouter(prefix="/api/projects", tags=["projects"])

GENERATED_ROOT = Path(__file__).resolve().parents[2] / "generated_projects"


def _readme_content(name: str) -> str:
    return (
        f"# {name}\n\n"
        "Generated by **IntelliYash** — Local AI Dev Studio.\n\n"
        "## Run Backend\n\n"
        "```bash\ncd backend\npip install -r requirements.txt\nuvicorn main:app --reload\n```\n\n"
        "## Run Frontend\n\n"
        "```bash\ncd frontend\nnpm install\nnpm run dev\n```\n\n"
        "## About\n\nAuto-generated project. Edit freely!\n"
    )


_ENV_EXAMPLE = (
    "# Environment variables\n"
    "# Copy this file to .env and fill in your values.\n\n"
    "# DATABASE_URL=sqlite:///./app.db\n"
    "# SECRET_KEY=change-me\n"
    "# DEBUG=false\n"
)


def _fs_projects() -> list[dict]:
    """Scan generated_projects/ and return one record per folder."""
    if not GENERATED_ROOT.exists():
        return []
    result = []
    for folder in sorted(GENERATED_ROOT.iterdir()):
        if not folder.is_dir():
            continue
        rel = f"backend/generated_projects/{folder.name}"
        result.append({
            "name": folder.name,
            "path": rel,
            "run_backend": (
                f"cd {rel}/backend\n"
                "pip install -r requirements.txt\n"
                "uvicorn main:app --reload"
            ),
            "run_frontend": (
                f"cd {rel}/frontend\n"
                "npm install\n"
                "npm run dev"
            ),
        })
    return result


@router.get("")
def list_projects():
    """Return projects merged from filesystem scan + persistent store."""
    from app.services.project_store import load_projects, register_project

    fs = {p["name"]: p for p in _fs_projects()}

    # Register any on-disk projects not yet in the store (idempotent).
    store = {p["name"]: p for p in load_projects()}
    for name, rec in fs.items():
        if name not in store:
            register_project(rec)
            store[name] = rec

    # Return store order (most-recent first), skipping entries whose folder
    # was hard-deleted from disk.
    ordered = [p for p in load_projects() if p["name"] in fs or p["name"] in store]
    return {"projects": ordered}


@router.get("/{name}/files")
def list_project_files(name: str):
    folder = (GENERATED_ROOT / name).resolve()
    if not str(folder).startswith(str(GENERATED_ROOT.resolve())):
        raise HTTPException(status_code=400, detail="Invalid project name")
    if not folder.exists() or not folder.is_dir():
        raise HTTPException(status_code=404, detail="Project not found")
    files = sorted(
        str(f.relative_to(folder)).replace("\\", "/")
        for f in folder.rglob("*")
        if f.is_file()
    )
    return {"files": files}


# ── File content (read-only preview) ──────────────────────────────────────

_TEXT_EXTENSIONS = {
    ".py", ".txt", ".md", ".json", ".yaml", ".yml", ".toml",
    ".js", ".ts", ".tsx", ".jsx", ".html", ".css", ".sh",
    ".cfg", ".ini", ".conf", ".sql", ".csv", ".xml", ".env",
}
_MAX_PREVIEW_BYTES = 200_000  # 200 KB


@router.get("/{name}/file")
def read_project_file(name: str, path: str):
    """Return the text content of a single file for read-only preview."""
    folder = (GENERATED_ROOT / name).resolve()
    root   = GENERATED_ROOT.resolve()
    if not str(folder).startswith(str(root)):
        raise HTTPException(status_code=400, detail="Invalid project name")
    if not folder.exists():
        raise HTTPException(status_code=404, detail="Project not found")

    target = (folder / path).resolve()
    if not str(target).startswith(str(folder)):
        raise HTTPException(status_code=400, detail="Path traversal not allowed")
    if not target.exists() or not target.is_file():
        raise HTTPException(status_code=404, detail="File not found")

    # Allow common text extensions plus special dot-files.
    ext = target.suffix.lower()
    allowed_names = {".env.example", ".gitignore", ".dockerignore", ".editorconfig"}
    if ext not in _TEXT_EXTENSIONS and target.name not in allowed_names:
        raise HTTPException(status_code=415, detail="Binary files cannot be previewed")

    if target.stat().st_size > _MAX_PREVIEW_BYTES:
        raise HTTPException(status_code=413, detail=f"File too large (>{_MAX_PREVIEW_BYTES // 1024} KB)")

    content = target.read_text(encoding="utf-8", errors="replace")
    return {"content": content, "path": path}


@router.get("/{name}/download")
def download_project(name: str):
    folder = (GENERATED_ROOT / name).resolve()
    if not str(folder).startswith(str(GENERATED_ROOT.resolve())):
        raise HTTPException(status_code=400, detail="Invalid project name")
    if not folder.exists() or not folder.is_dir():
        raise HTTPException(status_code=404, detail="Project not found")

    buf = io.BytesIO()
    with zipfile.ZipFile(buf, "w", zipfile.ZIP_DEFLATED) as zf:
        existing_arcs: set[str] = set()
        for file in folder.rglob("*"):
            if file.is_file():
                arc = str(file.relative_to(folder)).replace("\\", "/")
                zf.write(file, arc)
                existing_arcs.add(arc)
        # Inject README.md and .env.example if the project doesn't have them.
        if "README.md" not in existing_arcs:
            zf.writestr("README.md", _readme_content(name))
        if ".env.example" not in existing_arcs:
            zf.writestr(".env.example", _ENV_EXAMPLE)
    buf.seek(0)

    return StreamingResponse(
        buf,
        media_type="application/zip",
        headers={"Content-Disposition": f"attachment; filename={name}.zip"},
    )


@router.delete("/{name}")
def delete_project(name: str, delete_files: bool = False):
    """Remove a project from the store.
    Pass ?delete_files=true to also wipe the folder from disk.
    """
    folder = (GENERATED_ROOT / name).resolve()
    if not str(folder).startswith(str(GENERATED_ROOT.resolve())):
        raise HTTPException(status_code=400, detail="Invalid project name")

    from app.services.project_store import remove_project
    remove_project(name)          # no-op if already absent from store

    files_removed = False
    if delete_files and folder.exists():
        shutil.rmtree(folder)
        files_removed = True

    return {"status": "deleted", "name": name, "files_removed": files_removed}
